version: '2'
services:
  okimochi:
    build: ./okimochi
    image: joemphilips/okimochi:latest
    env_file: .env
    command: npm start
    extra_hosts:
      - "mongo:${MONGO_URI}"
      - "bitcoind:${BITCOIND_URI}"
    restart: on-failure
    environment:
      - NODE_ENV
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.2
    tty: true
    stdin_open: true
    depends_on:
      - bitcoind
      - mongo
  bitcoind:
    image: seegno/bitcoind:0.14.2-alpine
    volumes:
      - "${BITCOIND_HOST_DIR}:/home/bitcoin/.bitcoin"
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.3
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18444:18444"
    command:
      -printtoconsole
      -rest
      -txconfirmtarget=20
      -${BITCOIND_NETWORK}
      -server
      -rpcuser=${BITCOIND_USERNAME}
      -rpcpassword=${BITCOIND_PASSWORD}
      -rpcallowip=172.0.0.0/8
      -datadir=/home/bitcoin/.bitcoin
      -dbcache=500
      -prune=600
      -rpcthreads=8
      -assumevalid=00000000000000000026c661d175ef328e415e834e62f3d316382e9f3d24e44e
  mongo:
    restart: always
    image: mongo:3.4
    networks:
      okimochi-network:
        ipv4_address: 172.0.0.4
    command:
      --dbpath=/data/db
      --rest
    volumes:
      - "./userdb:/data/db"

networks:
  okimochi-network:
    external: true
